pnpm i module
pnpm i os
pnpm i loader
pnpm i ms
pnpm i moment
pnpm i moment-duration-format
pnpm i loader.js
npm i dateformat
npm  i common-tags
pnpm i common-tags
pnpm i node-superfetch
npm i node-superfetch
npm i parse-ms
npm i request
pnpm i ../events/5-otoTag 
npm i canvas
pnpm i simple-youtube-api
pnpm i ytdl-core
npm i fs
npm i simple-youtube-api
pnpm i ytdl-core
npm i ytdl-core
npmi  canvas
npm i canvas
